title: Wrye-Code-Collection
description: Collection of all my Wrye Mash/Flash/Bash source code
# google_analytics: true
# show_downloads: true
theme: jekyll-theme-cayman

exclude: ['README.md']
gems:
  - jekyll-mentions
  - jekyll-relative-links
