title: Wrye-Code-Collection
description: Collection of Wrye Mash/Flash/Bash source code
exclude: ['README.md']
google_analytics:
exclude: [
  'pagebuilder/',
]
# show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
plugins:
  - jekyll-relative-links
